name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  pod-lib-lint:
    runs-on: macOS-latest
    strategy:
      matrix:
        podspec: [GoogleSignIn.podspec, GoogleSignInSwift.podspec]
        flag: [
          "", 
          "--use-libraries", 
          "--use-static-frameworks"
        ]
        include:
          - podspec: GoogleSignInSwift.podspec
            includePodspecFlag: "--include-podspecs='GoogleSignIn.podspec'"
    steps:
    - uses: actions/checkout@v2
    - name: Update Bundler
      run: bundle update --bundler
    - name: Install Ruby gems with Bundler
      run: bundle install
    - name: Lint podspec using local source
      run: |
        pod lib lint ${{ matrix.podspec }} --verbose \
           ${{ matrix.includePodspecFlag }}  ${{ matrix.flag }}

  spm-build-test:
    runs-on: macOS-latest
    strategy:
      matrix:
        sdk: ['macosx', 'iphonesimulator']
        include:
          - sdk: 'macosx'
            destination: '"platform=OS X,arch=x86_64"'
          - sdk: 'iphonesimulator'
            destination: '"platform=iOS Simulator,name=iPhone 11"'
    steps:
    - uses: actions/checkout@v2
    - name: Build unit test target
      run: |
        xcodebuild \
          -scheme GoogleSignIn-Package \
          -sdk ${{ matrix.sdk }} \
          -destination ${{ matrix.destination }} \
          build-for-testing
    - name: Run unit test target
      run: |
        xcodebuild \
          -scheme GoogleSignIn-Package \
          -sdk ${{ matrix.sdk }} \
          -destination ${{ matrix.destination }} \
          test-without-building

  swift-button-functional-test:
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: Samples/Swift/DaysUntilBirthday
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create xcconfig file
      shell: bash
      env:
        EMAIL_SECRET : secret_fake_email@gmail.com
        PASSWORD_SECRET : foobar
      run: |
        echo EMAIL_SECRET = $EMAIL_SECRET$'\n'PASSWORD_SECRET = $PASSWORD_SECRET >> DaysUntilBirthdayUITests(iOS)/Credentials.xcconfig
    - name: Build test target for Google Sign-in button for Swift
      run: |
        xcodebuild \
          -project DaysUntilBirthday.xcodeproj \
          build-for-testing \
          -scheme DaysUntilBirthday\(iOS\) \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 11'
    - name: Run test target for Google Sign-in button for Swift
      run: |
        xcodebuild \
          -project DaysUntilBirthday.xcodeproj \
          test-without-building \
          -scheme DaysUntilBirthday\(iOS\) \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 11'
